### PR TITLE
Add support for using normalkey in syscrypt mode

### PR DESCRIPTION
**Pull request by thejsa**
For decrypting verdata DERs -- code is perhaps not as optimised as it could be (a separate function was created) but works just fine.

linux64 and win32 (mingw) builds are attached in the Releases section of my fork

### CODE REVIEW

**Comment by JoshuaDoes** [comment]
Works perfectly for me.

**Comment by WinterMute** [comment]
Could you remove the special windows Makefile please? It's not necessary.

If you remove this line https://github.com/WinterMute/twltool/blob/master/Makefile#L7 and change g++ in this line https://github.com/WinterMute/twltool/blob/master/Makefile#L10 to $(CC) then you can just run `make CC=i686-w64-mingw32-gcc` (or `make CC=x86_64-w64-mingw32-gcc` for that matter)

Just force push when you've made the changes and they'll show up on the PR. For future reference though it's better to create a branch for PRs.

**Comment by thejsa** [comment]
Done.

Noted, thanks - I don't often make PRs, hehe, but thanks for letting me know.

**Comment by WinterMute** [comment]
Great job, thanks :)

**Pull request merged**
